
spring.application.name=cloudguard-backend

spring.datasource.url=jdbc:h2:file:./data/cloudguard-users
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.org.springframework.security=TRACE
